### ISSUE TITLE
How to fix the SSL lib issue

### ISSUE THREAD

**Issue by syrius01** [johndekroon/serializekiller#11]
Hi,

I know it's a known issue that some SSL libs gets the following error msg;

 ! WARNING: Your SSL lib isn't supported. Results might be incomplete.

The question would be how to fix our SSL libs to work 100% with serializekiller ?

Thanks for your time,

syrius01

**Comment by johndekroon** [comment]
Hi Syrius01,

You need a SSL lib that supports create_default_context(). 
Which one do you use?

**Comment by syrius01** [comment]
apt-cache policy openssl
openssl:
  Installed: 1.0.1f-1ubuntu2.21
  Candidate: 1.0.1f-1ubuntu2.22
  Version table:
     1.0.1f-1ubuntu2.22 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
 *** 1.0.1f-1ubuntu2.21 0
        100 /var/lib/dpkg/status
     1.0.1f-1ubuntu2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

**Comment by syrius01** [comment]
Now I get:

 ! Could not check Jenkins on https. Maybe your SSL lib is broken.

Any help would be appreciated,

Thanks

**Comment by syrius01** [comment]
Used another linux distrib (Kali Linux) and it's all good.
